name: Generate Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          cd {{cookiecutter.project_name}}
          pip install -r requirements.txt

      - name: Run main script
        run: |
          cd {{cookiecutter.project_name}}/docs/maker_documentation
          python main.py

      - name: Commit and push changes
        run: |
          cd cookiecutter/docs
          git add md_docs/software-list.md
          git add md_docs/soup-list.md
          git commit -m 'Update documentation files' || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
